name: Vipercam Website Orchestration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # IONOS Deploy Now bot trigger
  repository_dispatch:
    types: [ionos-deploy]

jobs:
  build:
    uses: ./.github/workflows/ionos-deploy.yml
